### ISSUE TITLE
Update branch names to use main instead of master

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/git-novice-branch-pr#20]

**Comment by sstevens2** [comment]
There have been nice changes on this front merged into the main SWC git lesson.  We should rebase or incorporate those directly.

**Comment by sstevens2** [comment]
This really needs to be done asap - would like to reuse the material from the swc/git-novice lesson: the setup page about setting default branch and then the checking out main from the repo init section

**Comment by erwinlares** [comment]
would just adding this extra line to the git config part of the workshop fix this? 
git config --global init.defaultBranch "main"

**Comment by sstevens2** [comment]
Yes this is in the setup section I want to steal from.  For older versions of git that don't have it we will still need the checking out I mentioned as well.

**Comment by srappel** [comment]
The windows installer now includes an option to set the default branch to main. I'm going to include it in my revisions to the setup page, but mac and Linux users, or folks who already have git installed, will still benefit from the changes in your PR.
