### ISSUE TITLE
Bug in Lesson 9: Remotes

### ISSUE THREAD

**Issue by aayux** [carpentries-incubator/git-novice-branch-pr#23]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

I noticed a bug while preparing for a workshop recently. In lesson 9, "[Remotes with Github](https://uw-madison-datascience.github.io/git-novice-custom/09-github/)". Under `git clone`, line 295 in the [markdown](https://github.com/UW-Madison-DataScience/git-novice-custom/edit/gh-pages/_episodes/09-github.md): `git log --oneline` will not run correctly without first changing into the newly cloned planets/ directory. I know this is a minor issue in a really old fork, but I wanted to make sure this was bug was documented.

\- TC Instructor

**Comment by sstevens2** [comment]
Thanks @aayux !  Think I fixed this will commit https://github.com/carpentries-incubator/git-novice-branch-pr/commit/fb676ef809d8bbac3e7a080fbbcfbee6af69eeac.  I'll go ahead and close but feel free to reopen if you don't feel like it is fixed.
